# Generated by Django 3.1.3 on 2021-08-11 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20210811_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.detailinfo'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
