# Generated by Django 3.1.3 on 2021-08-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_auto_20210811_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
