# Generated by Django 3.1.3 on 2021-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0008_auto_20210811_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
