# Generated by Django 3.1.3 on 2021-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0013_auto_20210812_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(null=True),
        ),
    ]
