# Generated by Django 3.1.3 on 2021-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0014_auto_20210812_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
