# Generated by Django 3.1.3 on 2021-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0015_auto_20210812_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='render_subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
