# Generated by Django 3.1.3 on 2021-08-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0017_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='content',
            new_name='comment_text',
        ),
    ]
